CREATE TABLE Persons (
PersonID INT IDENTITY ,
FirstName VARCHAR(50) NOT NULL,
Salary MONEY NOT NULL,
PassportID INT NOT NULL
)

CREATE TABLE Passports (
PassportID INT NOT NULL,
PassportNumber VARCHAR(20) NOT NULL
)
ALTER TABLE Passports
ADD CONSTRAINT pk_Passports PRIMARY KEY (PassportID)

ALTER TABLE Persons
ADD CONSTRAINT pk_Persons PRIMARY KEY (PersonID)
ALTER TABLE Persons
ADD CONSTRAINT fk_Persons_Passports FOREIGN KEY (PassportID) REFERENCES Passports(PassportID)

INSERT INTO Passports VALUES
(101, 'N34FG21B'), (102, 'K65LO4R7'), (103, 'ZE657QP2')

INSERT INTO Persons
VALUES
('Roberto', 43300.00, 102), ('Tom', 56100.00, 103),('Yana', 60200.00, 101)